name: Update CN IP whitelist

on:
  schedule:
    # UTC 16:00 对应 UTC+8 00:00
    - cron: "0 16 * * *"
  workflow_dispatch: # 允许手动触发

env:
  OUTPUT_WHITE_LIST_PATH: "./output/white-list-cn.conf"

jobs:
  build:
    name: Update CN IP whitelist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout geo2-ip branch
        uses: actions/checkout@v4
        with:
          ref: geo2-ip
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run fetch script
        run: bash geo2-ip/geo2-cn-ip-fetch.sh
        env:
          MAXMIND_ACCOUNT_ID: ${{ secrets.MAXMIND_ACCOUNT_ID }}
          MAXMIND_LICENSE: ${{ secrets.MAXMIND_LICENSE }}

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./output/white-list-cn.conf
          if ! git diff-index --quiet HEAD --; then
            git commit -m "chore: auto-update CN IPv4 whitelist $(date +%F)"
            git push origin geo2-ip
          else
            echo "No changes to commit."
          fi

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Verify IPs with Python
        run: python3 geo2-ip/verify_cn_ip.py
        env:
          TEST_CN_IPS: ${{ secrets.TEST_CN_IPS }}
          TEST_FOREIGN_IPS: ${{ secrets.TEST_FOREIGN_IPS }}
